# @package _global_
type: prerender

prerender_method: MyModel
data_dir: "data/wall_open/"                       # where your mesh.obj saves
batch_size: 1
body_names: ['wall_open_filled']                          # your mesh.obj name
sphere_radius: 1.2
maximum_body_diameter: 2.4

#wall_open
#sphere_radius: 1.2
#maximum_body_diameter: 1.2
#latest_version: wall_open_filled

#four_way
#sphere_radius: 1.8
#maximum_body_diameter: 1.2
#lastest_version: fourway_filter

#one_way
#sphere_radius: 2.0
#maximum_body_diameter: 2.0
#latest_version: oneway_filter

#whisen_view
#sphere_radius: 2.4
#maximum_body_diameter: 2.4
#latest_version: whisenview_simplified_filled

geometry_unit_in_meter: 1.0                # the mesh.obj will be transformed in the unit in meter
                                             # for example: if the mesh.obj is in cm, then geometry_unit_in_meter = 0.01;
                                             # if the mesh.obj is in mm, then geometry_unit_in_meter = 0.001;
image_size: 1000 #원래 2000
image_border_size: 20 #원래 20
n_divide: 4
normalize_to_origin: False                   # fixed
num_sample_contour_point: 200
k_min_contour_length: 15
k_contour_normal_approx_radius: 3
output_mask: True                           # output the mask of each viewpoints if True
output_depth: False                          # Fixed
output_depth_vertex: False                   # output the inverse projected vertex of the depth of each viewpoints if True